---
title: "finalproject"
author: "William Paul"
date: "July 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readr)
library(dplyr)
library(stringr)
mutateyears = function(data, year) {
  mutate(data, DATASET_YEAR=year)
}
files03 = paste("hads", c(seq(2003, 2013, by = 2)), ".bz2", sep ="")
files03 = lapply(lapply(files03, read_csv), data.frame, stringsAsFactors= F)
files03 = mapply(mutateyears, files03, as.list(seq(2003,2013,by=2)))
new2011 = files03[[4]] %>% select(-VCHRMOV)
modernfiles = rbind(do.call(rbind, files03[c(1,2,3,5,6)]), new2011)
files85 = lapply(paste("hads", c(seq(1985, 1995, by = 2)), ".bz2", sep =""), read_csv)
files85 = lapply(files85, data.frame, stringsAsFactors= F)
new1995 = files85[[6]] %>% mutate(L30 = 0.6 * L50, GL30 = 0.6 * GL50, ABL30 = 0.6 * ABL50) %>%  rename("AGE1"=`AGE`, "FMTMETRO3" =`FMTMETRO`, "STATUS"=`ISTATUS`, "METRO3"=`METRO`)
files85 = lapply(files85[1:5], function(x){mutate(x, L30 = 0.6 * L50, GL30 = 0.6 * GL50, ABL30 = 0.6 * ABL50) %>%  rename("AGE1"=`AGE`, "FMTMetro3" = `FMTMetro`, "STATUS"=`ISTATUS`, "METRO3"=`METRO`)})
files85 = append(files85, list(new1995))
files85 = mapply(mutateyears, files85, as.list(seq(1985,1995,by=2)), SIMPLIFY = FALSE)
files85 = lapply(files85, function(x){setNames(x, (toupper(names(x)) %>% str_replace("^COSTMED(.+)", "COSTMed\\1")))})
files85 = lapply(files85, select_, .dots=names(modernfiles))
files95 = lapply(paste("hads", c(seq(1997, 2001, by = 2)), ".bz2", sep =""), read_csv)
files95 = lapply(files95, data.frame, stringsAsFactors= F)
files95 = lapply(files95, function(x){mutate(x, L30 = 0.6 * L50, GL30 = 0.6 * GL50, ABL30 = 0.6 * ABL50)})
files95 = mapply(mutateyears, files95, as.list(seq(1997,2001,by=2)), SIMPLIFY = FALSE)
files95 = lapply(files95, function(x){setNames(x, (toupper(names(x)) %>% str_replace("^COSTMED(.+)", "COSTMed\\1")))})
files95 = lapply(files95, select_, .dots=names(modernfiles))
oldfiles1 = do.call(rbind, files96)
oldfiles2 = do.call(rbind, files85)
totalfiles = rbind(rbind(oldfiles1, oldfiles2), modernfiles)
write_csv(totalfiles, "../data/cleaned_years.csv")
```